version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AUTO_SOUTHWEST_CHECK_IN_CHECK_FARES=false
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
