app = "southwest-checkin"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile.fly"

[env]
  AUTO_SOUTHWEST_CHECK_IN_CHECK_FARES = "false"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[processes]
  web = "python cloud-app.py"
  scheduler = "python scheduler.py"
