name: Format

on:
  push:
    branches:
      - master
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/format.yml"
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/format.yml"

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: isort
        uses: isort/isort-action@master

  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: black
        uses: psf/black@stable
