name: Lint + Format

on:
  push:
    branches:
      - master
      - develop
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/lint-format.yml"
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/lint-format.yml"

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: isort
        uses: isort/isort-action@v1.1.0
        with:
          requirements-files: "requirements.txt"

  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: black
        uses: psf/black@stable

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8
        uses: py-actions/flake8@v2
