name: Run unit tests

on:
  push:
    branches:
      - master
      - develop
    paths:
      - "**.py"
      - "**/requirements.txt"
      - ".github/workflows/tests.yml"
  pull_request:
    paths:
      - "**.py"
      - "**/requirements.txt"
      - ".github/workflows/tests.yml"

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -r tests/requirements.txt
      - name: Run unit tests
        run: pytest --cov --cov-fail-under=100
